### ISSUE TITLE
How to download the actions files

### ISSUE THREAD

**Issue by ayan-das1234** [danielhickman/MaterialDesign#3]
How to download the actions files

**Comment by danielhickman** [comment]
You need to download the `raw` version.

1. Go to the file you want to download.
2. Click it to view the contents within the GitHub UI.
3. In the top right, right-click the Raw button. (Should download or lead you to a page like [this](https://raw.githubusercontent.com/danielhickman/MaterialDesign/master/Actions/Shades.aia))
4. If it doesn't download immediately, right-click > `Save as`
5. To make sure the file is readable by Illustrator by removing the `.txt` at the end of the file name if it was added.

[Source and further reading](https://stackoverflow.com/a/13593430/2758250)

Also if you need to download multiple files from the same repo, cloning via git/GitHub Desktop or [downloading an entire branch](https://github.com/danielhickman/MaterialDesign/archive/master.zip) might be helpful as well.

**Comment by danielhickman** [comment]
I added information to the README.md in the root directory. Let me know if this isn't helpful so I can edit the README.

**Comment by ayan-das1234** [comment]
BTW are you any social media platform cause I am a rookie and I need a little help on an icon I was designing I am unable to use the actions properly

**Comment by danielhickman** [comment]
[Twitter](https://twitter.com/danielhickman9) and [Telegram](https://t.me/danielhickman) are good was of contacting me.

**Comment by ayan-das1234** [comment]
Yeah I saw that your Google+ posts is limited to one full webpage
